### ISSUE TITLE
The example segfaults.

### ISSUE THREAD

**Issue by andrejpodzimek** [felicianotech/go-lguf#1]
Steps taken to run the Usage [example](https://github.com/felicianotech/go-lguf#usage):

```bash
go mod init podzimek.org/m
# ... example placed in main.go ...
go mod tidy
sudo go run ./main.go
```

The outcome:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a1436]

goroutine 1 [running]:
github.com/google/gousb.(*Device).SetAutoDetach(0x0, 0x9a400401, 0x0, 0x0)
        /root/go/pkg/mod/github.com/google/gousb@v0.0.0-20190812193832-18f4c1d8a750/device.go:280 +0x26
github.com/felicianotech/go-lguf/lguf.NewConnection(0x0, 0x50c0e0, 0x50c0e0)
        /root/go/pkg/mod/github.com/felicianotech/go-lguf/lguf@v0.1.0/lguf.go:33 +0xfb
main.main()
        /home/apodzimek/inst/darkness/main.go:12 +0x34
exit status 2
```

[Here's a full `strace -f`.](https://github.com/felicianotech/go-lguf/files/4682896/strace.txt)

**Comment by mennis** [comment]
This is likely because the DID is wrong. Check the output of lsub to find the correct DID.  In my case it was 0x9a63 as seen here: 

```
% lsusb | grep LG
Bus 009 Device 006: ID 043e:9a63 LG Electronics USA, Inc.
Bus 009 Device 004: ID 043e:9a64 LG Electronics USA, Inc. USB2.1 Hub
Bus 009 Device 003: ID 043e:9a62 LG Electronics USA, Inc.
Bus 009 Device 002: ID 043e:9a61 LG Electronics USA, Inc. USB2.1 Hub
```

**Comment by FelicianoTech** [comment]
Hey. Apologies for replying years later. I was going to get this project back going but I have since found a better solution. Check out this project's readme: https://github.com/felicianotech/go-lguf
